# Use root/example as user/password credentials
services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - 27050:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db
